# Generated by Django 4.2.20 on 2025-04-01 18:16

import applications.common.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Внешний вид')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='appearance_icons/', verbose_name='Цвета')),
            ],
            options={
                'verbose_name': 'Внешний вид',
                'verbose_name_plural': 'Внешние виды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название атрибута')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='CommercialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Тип коммерческих машин',
                'verbose_name_plural': 'Типы коммерческих машин',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.CharField(unique=True, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'привод',
                'verbose_name_plural': 'приводы',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(unique=True, verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'двигатель',
                'verbose_name_plural': 'двигатели',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Медиа')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Тип мото',
                'verbose_name_plural': 'Типы мото',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Опции')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='color_icons/', verbose_name='Цвета')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_info', models.CharField(unique=True, verbose_name='Прочее')),
            ],
            options={
                'verbose_name': 'прочее',
                'verbose_name_plural': 'прочее',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Безапасность')),
            ],
            options={
                'verbose_name': 'Безапасность',
                'verbose_name_plural': 'Безапасность',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(unique=True, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'серия',
                'verbose_name_plural': 'серии',
            },
        ),
        migrations.CreateModel(
            name='SpecialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Тип спецтехники',
                'verbose_name_plural': 'Типы спецтехники',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(unique=True, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'коробка передач',
                'verbose_name_plural': 'коробки передач',
            },
        ),
        migrations.CreateModel(
            name='VehicleAd',
            fields=[
                ('public_id', models.CharField(default=applications.common.models.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(choices=[('new', 'новое'), ('good', 'хорошее'), ('ideal', 'идеальное'), ('crushed', 'аварийное/не на ходу')], default='good', max_length=10, verbose_name='Состояние')),
                ('mileage', models.PositiveIntegerField(help_text='Пробег в километрах', verbose_name='Пробег')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('availability_in_KG', models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'На заказ'), ('on_way', 'В пути')], default='in_stock', max_length=10, verbose_name='Наличие в Кыргызстане')),
                ('cleared_in_KG', models.BooleanField(default=True, verbose_name='Расстаможен в Кыргызстане')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN-код')),
                ('plate', models.CharField(blank=True, max_length=12, null=True, verbose_name='Гос номер авто')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('installment_payment', models.BooleanField(default=False, verbose_name='Возможность рассрочки')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Премиум объявление')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('link_Youtube', models.URLField(blank=True, max_length=2048, verbose_name='Ссылка YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='активный')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vehicle_qrcodes/', verbose_name='QR-code')),
                ('appearance', models.ManyToManyField(blank=True, related_name='appearance', to='vehicle.appearance', verbose_name='Внешний вид')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_city', to='common.city', verbose_name='город/село')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='body_type_icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True, verbose_name='Цвет')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='color_icons/', verbose_name='Цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('passenger', 'легковые'), ('commercial', 'коммерческие'), ('special', 'спец.техника'), ('moto', 'мотоциклы')], max_length=255, verbose_name='Название')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vehicle_logos/', verbose_name='Логотип')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make_country', to='common.countryname', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Марка Транспорта',
                'verbose_name_plural': 'Марки Транспорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vehicle_model_details/', verbose_name='картинка')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicle.vehiclemake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Года выпусков',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_images', to='vehicle.vehiclemodel', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-is_main'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='vehicle.attribute', verbose_name='Атрибут')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_model_detail', to='vehicle.vehiclemodel', verbose_name='характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.vehiclead', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-is_main'],
            },
        ),
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vehicle_generation_pictures/', verbose_name='Картинка')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_type', to='vehicle.vehiclebodytype', verbose_name='Поколение')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_color', to='vehicle.vehiclecolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vahicle_ad_currency', to='common.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.exchange', verbose_name='Возможность обмена'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Последнее обновление пользователем'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.vehiclemake', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='media', to='vehicle.media', verbose_name='Медиа'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.vehiclemodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='option',
            field=models.ManyToManyField(blank=True, related_name='option', to='vehicle.option', verbose_name='Опция'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='other_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_other_info', to='vehicle.otherinfo', verbose_name='Прочее'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_region', to='common.region', verbose_name='регион'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='registration_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_registration', to='common.countryname', verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='safety',
            field=models.ManyToManyField(blank=True, related_name='safety', to='vehicle.safety', verbose_name='Безапасность'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='salon',
            field=models.ManyToManyField(blank=True, related_name='salon', to='vehicle.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ad_subscription', to='common.subscription', verbose_name='подписка'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления'),
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_year', to='vehicle.vehicleyear', verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с +996, за которым следуют 9 цифр. Пример: +996700123456', regex='^\\+996\\d{9}$')], verbose_name='телефон')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_phones', to='vehicle.vehiclead', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.AddIndex(
            model_name='vehiclead',
            index=models.Index(fields=['make', 'model'], name='vehicle_veh_make_id_327467_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclead',
            index=models.Index(fields=['is_active', 'created_at'], name='vehicle_veh_is_acti_a35efe_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclead',
            index=models.Index(fields=['price'], name='vehicle_veh_price_15d22c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclead',
            index=models.Index(fields=['year', 'city'], name='vehicle_veh_year_id_c32ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclead',
            index=models.Index(fields=['user'], name='vehicle_veh_user_id_096d7b_idx'),
        ),
    ]
