# Generated by Django 4.2.20 on 2025-04-06 18:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение'),
        ),
    ]
