# Generated by Django 4.2.20 on 2025-04-06 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclead',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='QR-код'),
        ),
    ]
