# Generated by Django 4.2.20 on 2025-04-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='land', max_length=255, verbose_name='тип недвижимости')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='площадь участка, соток')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='RoomAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='room', max_length=255, verbose_name='тип недвижимости')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='площадь участка')),
                ('living_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='жилая площадь')),
                ('kitchen_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='площадь кухни')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_ad_floor', to='real_estate.floor', verbose_name='этаж')),
                ('max_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_ad_max_floor', to='real_estate.floor', verbose_name='количество этажей')),
                ('room_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_ad_location', to='real_estate.roomlocation', verbose_name='Расположение')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_ad_rooms', to='real_estate.roomtype', verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='ParkingAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='parking_garage', max_length=255, verbose_name='тип недвижимости')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_ad_residential_complex', to='real_estate.residentialcomplex', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'Паркинг',
                'verbose_name_plural': 'Паркинг',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='house', max_length=255, verbose_name='тип недвижимости')),
                ('area', models.PositiveSmallIntegerField(verbose_name='площадь дома m2')),
                ('total_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='площадь участка, соток')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_ad_building_type', to='real_estate.buildingtype', verbose_name='Тип строения')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_floor', to='real_estate.floor', verbose_name='этаж')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_ad_rooms', to='real_estate.roomtype', verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='DachaAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='cottage', max_length=255, verbose_name='тип недвижимости')),
                ('area', models.PositiveSmallIntegerField(verbose_name='площадь дачи m2')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='общая площадь, соток')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dacha_ad_building_type', to='real_estate.buildingtype', verbose_name='Тип строения')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dacha_ad_rooms', to='real_estate.roomtype', verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Дача',
                'verbose_name_plural': 'Дачи',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='CommercialAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='commercial', max_length=255, verbose_name='тип недвижимости')),
                ('area', models.PositiveSmallIntegerField(verbose_name='площадь коммерческой недвижимости m2')),
                ('total_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='площадь участка')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_ad_building_type', to='real_estate.buildingtype', verbose_name='Тип строения')),
                ('construction_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_year', to='real_estate.year', verbose_name='год постройки')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_floor', to='real_estate.floor', verbose_name='этаж')),
                ('max_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_max_floor', to='real_estate.floor', verbose_name='количество этажей')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_ad_object_type', to='real_estate.objecttype', verbose_name='Тип объекта')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_ad_residential_complex', to='real_estate.residentialcomplex', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'Коммерческое помещение',
                'verbose_name_plural': 'Коммерческие помещения',
            },
            bases=('real_estate.realestatead',),
        ),
        migrations.CreateModel(
            name='ApartmentAd',
            fields=[
                ('realestatead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='real_estate.realestatead')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('property_type', models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом'), ('commercial', 'коммерция'), ('room', 'комната'), ('land', 'участок'), ('cottage', 'дача'), ('parking/garage', 'паркинг/гараж')], default='apartment', max_length=255, verbose_name='тип недвижимости')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='общая площадь')),
                ('living_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='жилая площадь')),
                ('kitchen_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='площадь кухни')),
                ('building_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_ad_building_type', to='real_estate.buildingtype', verbose_name='Тип строения')),
                ('construction_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_year', to='real_estate.year', verbose_name='год постройки')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_floor', to='real_estate.floor', verbose_name='этаж')),
                ('max_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_max_floor', to='real_estate.floor', verbose_name='количество этажей')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_ad_residential_complex', to='real_estate.residentialcomplex', verbose_name='Жилой комплекс')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_ad_rooms', to='real_estate.roomtype', verbose_name='Количество комнат')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_ad_series', to='real_estate.series', verbose_name='Серия дома')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
            bases=('real_estate.realestatead',),
        ),
    ]
