# Generated by Django 4.2.20 on 2025-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='apartments', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='commercialad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='commercials', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='dachaad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='dachas', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='housead',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='houses', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='parkingad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='parkings', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='plotad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='plots', max_length=255, verbose_name='тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='roomad',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'квартира'), ('houses', 'дом'), ('commercials', 'коммерция'), ('rooms', 'комната'), ('plots', 'участок'), ('dachas', 'дача'), ('parkings', 'паркинг/гараж')], default='rooms', max_length=255, verbose_name='тип недвижимости'),
        ),
    ]
