# Generated by Django 4.2.20 on 2025-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_advertisement', '0002_alter_apartmentad_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialad',
            name='area',
        ),
        migrations.AlterField(
            model_name='commercialad',
            name='total_area',
            field=models.PositiveSmallIntegerField(default='200', verbose_name='площадь коммерческой недвижимости m2'),
            preserve_default=False,
        ),
    ]
