# Generated by Django 4.2.20 on 2025-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Клиент'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор'), ('COMPANY', 'Компания')], default='CUSTOMER', max_length=20, verbose_name='роль'),
        ),
    ]
