# Generated by Django 4.2.20 on 2025-04-02 10:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_remove_realestatead_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatead',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Точка на карте'),
        ),
    ]
