# Generated by Django 4.2.20 on 2025-04-06 19:06

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_alter_realestateadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatead',
            name='designing_docs',
            field=models.FileField(blank=True, help_text='архитектурное решение', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/', verbose_name='дизайн'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='measurements_docs',
            field=models.FileField(blank=True, help_text='точные замеры', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='real_estate/documents/', verbose_name='обмеры'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='QR-код'),
        ),
    ]
