# Generated by Django 4.2.20 on 2025-04-07 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0009_alter_realestatead_designing_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatead',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='realestatead',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL, verbose_name='Подтвержден: '),
        ),
        migrations.AddField(
            model_name='realestatead',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Подтвержденный'),
        ),
    ]
