# Generated by Django 4.2.20 on 2025-04-07 09:58

import applications.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_realestatead_approved_at_realestatead_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatead',
            name='public_id',
            field=models.CharField(default=applications.common.models.generate_short_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
