# Generated by Django 4.2.20 on 2025-04-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('real_estate', '0011_alter_realestatead_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestatead',
            name='location',
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_district', to='common.district', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_ads', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
