# Generated by Django 4.2.20 on 2025-04-10 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_remove_realestatead_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='qr_code',
            field=models.URLField(blank=True, max_length=900, null=True, verbose_name='QR-код PDF'),
        ),
        migrations.AddIndex(
            model_name='realestatead',
            index=models.Index(fields=['ad_type', 'is_active'], name='real_estate_ad_type_4397b8_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatead',
            index=models.Index(fields=['created_at', 'is_active'], name='real_estate_created_b1a749_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatead',
            index=models.Index(fields=['price', 'currency'], name='real_estate_price_4105e8_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatead',
            index=models.Index(fields=['city', 'district'], name='real_estate_city_id_b05fcc_idx'),
        ),
    ]
