# Generated by Django 4.2.20 on 2025-04-11 10:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_alter_realestatead_latitude_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='realestatead',
            new_name='real_estate_price_813c41_idx',
            old_name='real_estate_price_4105e8_idx',
        ),
        migrations.AddField(
            model_name='realestatead',
            name='price_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Цена в сомах'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар США'), ('KGS', 'Кыргызский сом')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
    ]
